### ISSUE TITLE
Should we validate the pubkeys parameters of `fast_aggregate_verify`?

### ISSUE THREAD

**Issue by ChihChengLiang** [sigp/milagro_bls#40]
Hi Kirk,

Currently, the `fast_aggregate_verify` returns `true` if the `aggregate_public_key` is an identity key because we don't run `key_validate` checks for the input public keys.

The IETF spec defines the behavior of FastAggregateVerify when the preconditions are met. But whether to check those preconditions are [left for implementors to decide](https://github.com/cfrg/draft-irtf-cfrg-bls-signature/issues/27#issuecomment-694554717).

Here are some options:

- In Eth2's [test cases](https://github.com/ethereum/eth2.0-specs/pull/2080/files#diff-4566979c41543cbb63ce756517fa208fR72), the validation is expected. It might be safer if all the client teams implement the same behavior.
- The [nim-blscurve](https://github.com/cfrg/draft-irtf-cfrg-bls-signature/issues/27#issuecomment-694072430) implements two versions, one with the check and one without.

**Comment by kirk-baird** [comment]
This is a good point. I think it is safe to not check these pre-conditions for `fast_aggregate_verify()`.
This is because one of the pre-conditions is that the public key is verified by proof of possession before calling `fast_aggregate_verify()`.

However since the check is so cheap it's beneficial to add it :)

Added in #41

**Comment by kirk-baird** [comment]
I have prevented `PublicKeys` from being infinity by doing subgroup checks and infinity checks during deserialisation so this should no longer be an issue.
